# Generated by Django 6.0.2 on 2026-04-16 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocorrencias', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocorrencia',
            name='comentario_fechamento',
            field=models.TextField(blank=True, null=True, verbose_name='Comentário de fechamento'),
        ),
    ]
