# Generated by Django 6.0.2 on 2026-05-18 15:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocorrencias', '0003_add_comentario_fechamento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ObservacaoNOC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente_slug', models.SlugField(max_length=120, verbose_name='Slug do cliente')),
                ('cliente_nome', models.CharField(max_length=200, verbose_name='Nome do cliente')),
                ('texto', models.TextField(verbose_name='Observação')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
            ],
            options={
                'verbose_name': 'Observação NOC',
                'verbose_name_plural': 'Observações NOC',
                'ordering': ['-criado_em'],
            },
        ),
    ]
