# Generated by Django 6.0.2 on 2026-05-18 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ocorrencias', '0004_add_observacao_noc'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ObservacaoNOC',
        ),
    ]
