# Generated by Django 6.0.2 on 2026-05-18 19:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocorrencias', '0005_delete_observacaonoc'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='glpi_user_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='ID do usuário no GLPI'),
        ),
        migrations.CreateModel(
            name='AutoResponseRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_id_origem', models.PositiveIntegerField(verbose_name='Problema de origem no GLPI')),
                ('problem_title', models.CharField(max_length=255, verbose_name='Título do alerta')),
                ('followup_text', models.TextField(verbose_name='Texto de resposta automática')),
                ('active_until', models.DateTimeField(verbose_name='Regra ativa até')),
                ('glpi_user_id', models.PositiveIntegerField(verbose_name='ID do usuário no GLPI')),
                ('enabled', models.BooleanField(default=True, verbose_name='Ativa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criada em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizada em')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Regra de Resposta Automática',
                'verbose_name_plural': 'Regras de Resposta Automática',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AutoResponseExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('glpi_problem_id', models.PositiveIntegerField(verbose_name='ID do problema no GLPI')),
                ('glpi_problem_title', models.CharField(max_length=255, verbose_name='Título do problema')),
                ('assignment_success', models.BooleanField(default=False, verbose_name='Atribuição executada')),
                ('followup_success', models.BooleanField(default=False, verbose_name='Followup executado')),
                ('response_payload', models.TextField(blank=True, default='', verbose_name='Resposta técnica')),
                ('executed_at', models.DateTimeField(auto_now_add=True, verbose_name='Executado em')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='ocorrencias.autoresponserule', verbose_name='Regra')),
            ],
            options={
                'verbose_name': 'Execução de Resposta Automática',
                'verbose_name_plural': 'Execuções de Resposta Automática',
                'ordering': ['-executed_at'],
                'constraints': [models.UniqueConstraint(fields=('rule', 'glpi_problem_id'), name='unique_rule_problem_execution')],
            },
        ),
    ]
