# Generated by Django 6.0.2 on 2026-05-18 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocorrencias', '0006_userprofile_glpi_user_id_autoresponserule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='autoresponserule',
            name='analyst_name',
            field=models.CharField(default='', max_length=255, verbose_name='Nome do analista'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='glpi_analyst_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome do analista no GLPI'),
        ),
    ]
